### ISSUE TITLE
Add follow button

### ISSUE THREAD

**Issue by b-lam** [b-lam/Resplash#15]

**Comment by LongJohn-Silver** [comment]
Why was this closed? I don't see it nowhere, or maybe is it hidden?

**Comment by b-lam** [comment]
@LongJohn-Silver Unfortunately the Unsplash API doesn't support it

**Comment by LongJohn-Silver** [comment]
So is there no way around this?

**Comment by b-lam** [comment]
Probably not without doing something super hacky :/

**Comment by LongJohn-Silver** [comment]
I was looking over the Unsplash website about their API and found this, I'm pretty sure it's pointless since big companies don't give a fuck about their users, generally, but do you think it's completely pointless to e-mail them to that address and maybe suggest to implement this into their API? I can send the e-mail if you want, but wanted to get some feedback first.

>Interested in using the Unsplash API for free in a high-volume application? Get in touch with our Partnerships team at partnerships@unsplash.com
