### ISSUE TITLE
Resplash auto wallpaper related problem.

### ISSUE THREAD

**Issue by Msizabian** [b-lam/Resplash#155]
Dear app developer,
Hope you are fine. I'm facing problem in app that it sometimes doesnt changes wallpaper several hours. When it doesnt changes then i have to open app and go in history of wallpapers... It changes after fe moments.. then app is good for several hours.
Oneplus 7 pro i'm using mobile phone.

**Comment by b-lam** [comment]
Hi @Msizabian, can you try disable any kind of battery optimizations for Resplash because it can cause issues with the background service running auto wallpaper. This website goes into detail about all the things that you might need to adjust to get it working https://dontkillmyapp.com/oneplus. I hope that helps :)

**Comment by Msizabian** [comment]
> Hi @Msizabian, can you try disable any kind of battery optimizations for Resplash because it can cause issues with the background service running auto wallpaper. This website goes into detail about all the things that you might need to adjust to get it working https://dontkillmyapp.com/oneplus. I hope that helps :)
> 

Thankyou soo much for guiding. My problem has been resolved. 🙂

**Comment by b-lam** [comment]
@Msizabian Awesome glad I could help! 🙂
