### ISSUE TITLE
App crash when downloading photo

### ISSUE THREAD

**Issue by KrazyCavin** [b-lam/Resplash#33]
- Install app
- Deny the storage permission
- Download image or set image as wallpaper

It's not a serious problem. However, it's better to not crash the app, isn't it?

A really nice app! Good job 👍

**Comment by jrmileham** [comment]
I had this issue too, but I did manage to solve it. It turned out that the app was crashing because it couldn't access the folder `/Pictures/Resplash/`. On my phone the folder was corrupted and appeared as a zero byte file. After deleting the file and recreating it as a folder, I was able to download and set as wallpaper.

**Comment by b-lam** [comment]
Fixed in v1.1.3
